version: '3.7'

services:
  code:
    container_name: course_code
    working_dir: /home/wwwroot/course
    build:
      context: ../../
      dockerfile: ops/docker/app/Dockerfile
      target: dev
    volumes:
      - socket:/socket
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
     # - ./conf/php/zzz-pool.conf:/usr/local/etc/php-fpm.d/zzz-pool.conf
      - ../../src/:/home/wwwroot/course
    networks:
      - backend
    user: nobody

networks:
  backend:

volumes:
  socket:
